name: Build

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  build:
    if: ${{startsWith(github.event.head_commit.message, 'WIP') != true}}

    services:
      mongodb:
        image: mongo:5.0.6
        ports:
          - 27017:27017

    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [ 1.36.0 ]

    steps:
      - uses: actions/checkout@v1
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: build and test
        run: |
          deno --version --unstable
          deno task test
          deno task coverage
        env:
          CI: true
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./docs/reports/coverage/lcov.info

