name: Node CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
      - 'releases/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: ./docs/reports/coverage/lcov.info
        github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Check if version has been updated
        uses: EndBug/version-check@v1
        id: check

      - run: npm ci
      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
          run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'