name: Publish

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:

  publish-prerelease:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [ 1.23.4 ]

    steps:
      - uses: actions/checkout@v2.3.2
        with:
          # fetch full history so things like auto-changelog work properly
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: publish
        run: |
          npm config set '//npm.justaos.com/:_authToken' "${{ secrets.JUSTAOS_NPM_TOKEN }}"
          npm config set @p4:registry https://npm.justaos.com
          npm ci
          npm run bootstrap
          npm run publish