name: "github-release"

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:

  prerelease:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "Github Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false